# Generated by Django 6.1.1 on 2026-10-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_language_level_alter_project_demo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
